apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: load-order-profile-api
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Kaifff04/argocd-load-error.git
    targetRevision: HEAD
    path: load-api
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
      
