# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: load-order-profile-api
#   namespace: myapp
#   labels:
#     app.kubernetes.io/name: load-order-profile-api
#     app.kubernetes.io/instance: load-order-profile-api
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app.kubernetes.io/instance: load-order-profile-api
#       app.kubernetes.io/name: load-order-profile-api
#       # app.kubernetes.io/component: deployment.yaml
#   template:
#     metadata:
#       labels:
#         app.kubernetes.io/instance: load-order-profile-api
#         app.kubernetes.io/name: load-order-profile-api
#         # app.kubernetes.io/component: deployment.yaml
#     spec:
#       containers:
#       - name: nginx
#         image: nginx:latest
#         command: ["sh", "-c", "sleep 400"]
#         ports:
#         - containerPort: 80
#         resources:
#           requests:
#             cpu: 500m

apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-order-profile-api
  namespace: myapp
  labels:
    app.kubernetes.io/name: load-order-profile-api
    app.kubernetes.io/instance: load-order-profile-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: load-order-profile-api
      app.kubernetes.io/name: load-order-profile-api
      # app.kubernetes.io/component: deployment.yaml
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: load-order-profile-api
        app.kubernetes.io/name: load-order-profile-api
        # app.kubernetes.io/component: deployment.yaml
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        command: ["sh", "-c", "sleep 400"]
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 500m
---
apiVersion: batch/v1
kind: Job
metadata:
  name: load-order-profile-api-db-migration
  namespace: myapp
  labels:
    app.kubernetes.io/name: load-order-profile-api
    app.kubernetes.io/instance: load-order-profile-api
    app.kubernetes.io/managed-by: Helm
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "-30" # Syncs before other resources
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation # Delete job before creating a new one
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-order-profile-api
        app.kubernetes.io/instance: load-order-profile-api
        # app.kubernetes.io/component: job.yaml
    spec:
      containers:
      - name: load-order-profile-api-db-migrate
        image: busybox
        command: ["sh", "-c", "sleep 5"]
        resources: {}
      restartPolicy: Never
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: load-order-profile-api
  namespace: myapp
  labels:
    app.kubernetes.io/instance: load-order-profile-api
    app.kubernetes.io/name: load-order-profile-api
  annotations:
    argocd.argoproj.io/sync-wave: "5" # Syncs before other resources
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: "BeforeHookCreation"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: load-order-profile-api
  minReplicas: 2
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
