apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-order-profile-api
  namespace: myapp
  labels:
    app.kubernetes.io/name: load-order-profile-api
    app.kubernetes.io/instance: load-order-profile-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: load-order-profile-api
      app.kubernetes.io/name: load-order-profile-api
      app.kubernetes.io/component: deployment.yaml
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: load-order-profile-api
        app.kubernetes.io/name: load-order-profile-api
        app.kubernetes.io/component: deployment.yaml
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        command: ["sh", "-c", "while true; do echo 'Running load...'; yes > /dev/null; done"]
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 500m

