apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-order-profile-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
            requests:
              cpu: 500m
        command: ["sh", "-c", "while true; do echo 'Running load...'; yes > /dev/null; done"]
