apiVersion: batch/v1
kind: Job
metadata:
  name: load-order-profile-api-db-migration
  namespace: default
  labels:
    app.kubernetes.io/name: load-order-profile-api
    app.kubernetes.io/instance: load-order-profile-api
    app.kubernetes.io/managed-by: Helm
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "-30" # Syncs before other resources
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation # Delete job before creating a new one
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-order-profile-api
        app.kubernetes.io/instance: load-order-profile-api
    spec:
      containers:
      - name: load-order-profile-api-db-migrate
        image: busybox
        command: ["sh", "-c", "while true; do echo 'Running load...'; yes > /dev/null; done"]
        resources: {}
      restartPolicy: Never
